### ISSUE TITLE
<iron-form> .validate() is not a function

### ISSUE THREAD

**Issue by drdreo** [PolymerElements/iron-form#196]
### Description
The `iron-form` element validation ain't working with polymer 2.0: . validate() is not a function. 

Validation through:
in the connectedCallback 

`  let eventsDemo = this.shadowRoot.getElementById('eventsDemo');` 
`
```
eventsDemo.addEventListener('change', function (event) 
{    
                    eventsDemoSubmit.disabled = !eventsDemo.validate();
                });
```
`

The change event gets triggered every time i change something in the form, but the validate can't be called.

> TypeError: eventsDemo.validate is not a function

The form:
```

<iron-form>
            <form method="get" action="/" id="eventsDemo">
                <paper-input name="name" label="Name" required auto-validate></paper-input>
                <paper-input name="password" label="Password" type="password" required auto-validate></paper-input>
                <paper-checkbox name="read" required>You must check this box</paper-checkbox>
                <br>
                <paper-button raised onclick="_delayedSubmit(event)" disabled id="eventsDemoSubmit">
                    <paper-spinner id="spinner" hidden></paper-spinner>
                    Submit
                </paper-button>
                <paper-button raised onclick="_reset(event)">Reset</paper-button>
                <div class="output"></div>
            </form>
        </iron-form>
```
### Browsers Affected

- [x ] Chrome

**Comment by notwaldorf** [comment]
Oh, you need to call `validate` on the `iron-form`, not on the nested native `<form>`
